apiVersion: v1
kind: ConfigMap
metadata:
  name: alpha-scada-config
  namespace: alpha-scada
data:
  ASPNETCORE_URLS: http://+:8080
  Region: EU
  Nats__Url: nats://nats:4222
  EdgeMqtt__Host: nats
  EdgeMqtt__Port: "1883"
  Simulator__Enabled: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: alpha-scada-secrets
  namespace: alpha-scada
type: Opaque
stringData:
  Jwt__Secret: replace-with-generated-jwt-secret
  Nats__User: services
  Nats__Password: services-pass
  NATS_USER_EDGE: edge
  NATS_PASSWORD_EDGE: edge-pass
  Simulator__MqttUser: edge
  Simulator__MqttPassword: edge-pass
