server_name: alpha-scada

port: 4222
http_port: 8222

jetstream {
  store_dir: "/data/jetstream"
  max_mem_store: 256M
  max_file_store: 2G
}

mqtt {
  port: 1883
}

authorization {
  users = [
    { user: "edge", password: "edge-pass" },
    { user: "services", password: "services-pass" },
    { user: "admin", password: "admin-pass" }
  ]
}
