listener 1883
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl

persistence true
persistence_location /mosquitto/data/
autosave_interval 60

max_inflight_messages 100
max_queued_messages 10000
queue_qos0_messages false

log_dest stdout
