FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG PROJECT
WORKDIR /src
COPY . .
RUN dotnet restore "$PROJECT"
RUN dotnet publish "$PROJECT" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0
ARG DLL
ENV SERVICE_DLL=$DLL
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT dotnet "$SERVICE_DLL"
